[server]
headless = true
port = 8501
enableCORS = false
fileWatcherType = "none"

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#EAEAEA"
textColor = "#000000"
font = "sans serif"

[logger]
level = "info"

[browser]
gatherUsageStats = false
