[server]
headless = true
enableCORS = false
port = 8501
maxUploadSize = 200

[fileWatcher]
watcherType = "none"

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#EAEAEA"
textColor = "#000000"
font = "sans serif"
