# Streamlit configuration file for TaxIntellilytics
# Forces polling to avoid inotify watch limit errors

[server]
# Use polling instead of inotify for file watching
fileWatcherType = "poll"

# Optional: Allow external access (for cloud deployments)
enableCORS = false
enableXsrfProtection = true
