[server]
# Disable Streamlit's file watcher to avoid inotify watch limit errors on Linux hosts
fileWatcherType = "none"

# Networking / security (adjust as needed)
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#EAEAEA"
textColor = "#000000"
font = "sans serif"

[logger]
level = "info"
